version: "3.8"
services:
  backend-flask:
    build: ./backend-flask
    ports:
      - "8000:8000"

    volumes:
      - ./backend-flask:/backend-flask

  frontend-react-js:
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./frontend-react-js:/frontend-react-js

networks:
  internal-networks:
    driver: bridge
    name: appNetwork
